### PR TITLE
Use least load node and fix stuck player

### PR DESCRIPTION
**Pull request by JirayuSrisawat-Github**

### CODE REVIEW

**Review by SxMAbel — CHANGES_REQUESTED** [review]
Using least node load isn't liked be everyone please add options to select between using least player node and least load node. Thanks!

Also did you test the changes you made before opening a pull request?

**Comment by JirayuSrisawat-Github** [comment]
I've done the test. And I think using nodes with less load will be better. Anyway, I'll do it according to your suggestion.

**Comment by JirayuSrisawat-Github** [comment]
I've added the option to 8695734.

**Comment by SxMAbel** [comment]
Don't forget to edit the docs: https://github.com/Blackfort-Hosting/magmastream_documentation

**Comment by JirayuSrisawat-Github** [comment]
I have edited it in https://github.com/Blackfort-Hosting/magmastream_documentation/pull/2

**Comment by SxMAbel** [comment]
> I have edited it in [Blackfort-Hosting/magmastream_documentation#2](https://github.com/Blackfort-Hosting/magmastream_documentation/pull/2)

I requested a change to make it default to use "leastPlayers"

**Review by SxMAbel — APPROVED** [review]

**Comment by SxMAbel** [comment]
code moved to my test workspace, will be merged once tests completes

**Pull request merged**
