### PR TITLE
Remove ClientUser type

### PR DESCRIPTION
**Pull request by BloomyInDev**
Remove `ClientUser` type from everywhere where `User | ClientUser` was.

When you have a Typescript codebase, it throw an error and says
> Type 'User' is missing the following properties from type 'ClientUser': mfaEnabled, presence, verified, edit, and 7 more.

`ClientUser` extends `User` so no need to add it in the types

It seems to build correctly on my computer

### CODE REVIEW

**Comment by SxMAbel** [comment]
> Remove `ClientUser` type from everywhere where `User | ClientUser` was.
> 
> When you have a Typescript codebase, it throw an error and says
> 
> > Type 'User' is missing the following properties from type 'ClientUser': mfaEnabled, presence, verified, edit, and 7 more.
> 
> `ClientUser` extends `User` so no need to add it in the types
> 
> It seems to build correctly on my computer

When setting a requester you have to pass the entire user object (interaction.user or client.user)

**Comment by BloomyInDev** [comment]
> > Remove `ClientUser` type from everywhere where `User | ClientUser` was.
> > When you have a Typescript codebase, it throw an error and says
> > > Type 'User' is missing the following properties from type 'ClientUser': mfaEnabled, presence, verified, edit, and 7 more.
> > 
> > 
> > `ClientUser` extends `User` so no need to add it in the types
> > It seems to build correctly on my computer
> 
> When setting a requester you have to pass the entire user object (interaction.user or client.user)

Yes but it still throw the same error :upside_down_face:

**Comment by SxMAbel** [comment]
Open help forum in discord

**Comment by BloomyInDev** [comment]
What does make this pull request invalid ?

**Comment by BloomyInDev** [comment]
Proof given, waiting for merge

**Comment by BloomyInDev** [comment]
Fixed personaly by using `any` type (yes it is bad)

**Pull request closed without merging**
